#!/usr/bin/env bash
PERMITS_DATA="$DATA_FOLDER/etl/permits"
TMP_FOLDER="$DATA_FOLDER/etl/permits/tmp"

#Read variables from config file
DB_HOST=$(cat $ROOT_FOLDER'/config.yaml' | shyaml get-value db.host)
DB_USER=$(cat $ROOT_FOLDER'/config.yaml' | shyaml get-value db.user)
DB_NAME=$(cat $ROOT_FOLDER'/config.yaml' | shyaml get-value db.database)

#create folder if not exists
mkdir -p $TMP_FOLDER

#Path to update script
UPDATE_SCRIPT=$ROOT_FOLDER/lib_cinci/data_updater/update.py
#Create diff file with entries to upload to the database
$UPDATE_SCRIPT $ROOT_FOLDER/etl/permits/update.yaml

#Clean data
python "$ROOT_FOLDER/etl/permits/clean.py"

#Geocode
echo 'Geocoding data, this may take a while...'
python "$ROOT_FOLDER/bulk_geocoder/geocode_csv.py" "$TMP_FOLDER/diff_permits_clean.csv" "$TMP_FOLDER/diff_permits_clean_geocoded.csv"

#Process geocoded file
echo 'Final processing...'
python "$ROOT_FOLDER/bulk_geocoder/process_geocoded_csv.py" "$TMP_FOLDER/diff_permits_clean_geocoded.csv" "$TMP_FOLDER/diff_permits_db.csv"

echo 'Generating CREATE TABLE statement...'
#Generate CREATE TABLE statement
csvsql -i postgresql --tables permits --db-schema public -d ',' "$TMP_FOLDER/diff_permits_db.csv" > "$TMP_FOLDER/permits.sql"
#Create table
psql -h $DB_HOST -U $DB_USER -d $DB_NAME < "$TMP_FOLDER/permits.sql"  
#Final processing for table
echo 'Processing table: adding index and unique id...'
psql -h $DB_HOST -U $DB_USER -d $DB_NAME < "$ROOT_FOLDER/etl/permits/process_table.sql"

echo 'Uploading data...'
#Get list of columns to cpy, this is necessary since we have a PRIMARY KEY
#and we want postgres to take care of those values
COLS="$(head -n 1 $TMP_FOLDER/diff_permits_db.csv)"
#Upload data to the database
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "\COPY public.permits($COLS) FROM $TMP_FOLDER/diff_permits_db.csv WITH CSV HEADER DELIMITER ',';"
echo 'Done.'