CREATE SCHEMA IF NOT EXISTS model_results;

DROP TABLE IF EXISTS model_results.all_models;
CREATE TABLE model_results.all_models (
    model_id VARCHAR NOT NULL,
    model_name VARCHAR,
    prec_at_1 numeric,
    prec_at_10 numeric,
    prec_at_20 numeric,
    prec_at_5 numeric,
    test_start date,
    validation_labeled_percent NUMERIC,
    validation_precision_at_k NUMERIC,
    experiment_name VARCHAR,
    features VARCHAR,
    grid_size VARCHAR,
    start_date DATE,
    validation_window VARCHAR,
    training_window varchar,
    C numeric,
    bootstrap boolean,
    class_weight BOOLEAN,
    criterion VARCHAR,
    dual VARCHAR,
    fit_intercept varchar,
    intercept_scaling varchar,
    max_depth numeric,
    max_features varchar,
    max_iter numeric,
    max_leaf_nodes numeric,
    min_samples_leaf numeric,
    min_samples_split numeric,
    min_weight_fraction_leaf numeric,
    multi_class VARCHAR,
    n_estimators NUMERIC,
    n_jobs NUMERIC,
    oob_score BOOLEAN,
    penalty VARCHAR,
    random_state NUMERIC,
    solver VARCHAR,
    tol NUMERIC,
    "verbose" BOOLEAN,
    warm_start BOOLEAN,
    model_number INT);


