#!/usr/bin/env bash
CRIME_CPD_FOLDER="$DATA_FOLDER/etl/crime"
TMP_FOLDER="$DATA_FOLDER/etl/crime/tmp"

#Read variables from config file
DB_HOST=$(cat $ROOT_FOLDER'/config.yaml' | shyaml get-value db.host)
DB_USER=$(cat $ROOT_FOLDER'/config.yaml' | shyaml get-value db.user)
DB_NAME=$(cat $ROOT_FOLDER'/config.yaml' | shyaml get-value db.database)

#mkdir if not exists
mkdir -p $TMP_FOLDER

echo "Converting data from $CRIME_CPD_FOLDER"
#Convert raw data files to csv and store results in tmp folder
ssconvert "$CRIME_CPD_FOLDER/crime.xlsx" "$CRIME_CPD_FOLDER/crime.csv"

#Path to update script
UPDATE_SCRIPT=$ROOT_FOLDER/lib_cinci/data_updater/update.py
#Create diff file with entries to upload to the database
$UPDATE_SCRIPT $ROOT_FOLDER/etl/crime/update.yaml

echo 'Cleaning data...'
#Perform cleaning on the  CSV file
python "$ROOT_FOLDER/etl/crime/clean.py"

echo 'Geocoding...'
#Geocode
python "$ROOT_FOLDER/bulk_geocoder/geocode_csv.py" "$TMP_FOLDER/diff_crime_clean.csv" "$TMP_FOLDER/diff_crime_geocoded.csv"
#Process geocoded file
python "$ROOT_FOLDER/bulk_geocoder/process_geocoded_csv.py" "$TMP_FOLDER/diff_crime_geocoded.csv" "$TMP_FOLDER/diff_crime_db.csv"

echo 'Generating CREATE TABLE statement...'
#Use csvsql to create a SQL script with the CREATE TABLE statement
csvsql -i postgresql --no-constraints --tables crime --db-schema public "$TMP_FOLDER/diff_crime_db.csv" > "$TMP_FOLDER/crime.sql"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME < "$TMP_FOLDER/crime.sql"  
echo 'Processing table: adding index and unique id...'
psql -h $DB_HOST -U $DB_USER -d $DB_NAME < "$ROOT_FOLDER/etl/crime/process_table.sql"  

echo 'Uploading data...'
#Get list of columns to cpy, this is necessary since we have a PRIMARY KEY
#and we want postgres to take care of those values
COLS="$(head -n 1 $TMP_FOLDER/diff_crime_db.csv)"
#Upload data to the database
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "\COPY public.crime($COLS) FROM $TMP_FOLDER/diff_crime_db.csv WITH CSV HEADER DELIMITER ',';"

echo 'Done.'
