#!/usr/bin/env bash
#This script requires mdbtools to be installed
LOCAL_DATA_FOLDER="$DATA_FOLDER/etl/fire"
TMP_FOLDER="$LOCAL_DATA_FOLDER/tmp"

#mkdir if tmp folder does not exists
mkdir -p $TMP_FOLDER

#Read variables from config file
DB_HOST=$(cat $ROOT_FOLDER'/config.yaml' | shyaml get-value db.host)
DB_USER=$(cat $ROOT_FOLDER'/config.yaml' | shyaml get-value db.user)
DB_NAME=$(cat $ROOT_FOLDER'/config.yaml' | shyaml get-value db.database)

#Download and concatenate files from 2012 to 2015
bash "$ROOT_FOLDER/etl/fire/download.sh"

#Clean data
python "$ROOT_FOLDER/etl/fire/clean.py"

echo 'Geocoding dataset, this may take a while...'
python "$ROOT_FOLDER/bulk_geocoder/geocode_csv.py" "$TMP_FOLDER/fire_clean.csv" "$TMP_FOLDER/fire_geocoded.csv"
#Process geocoded file
python "$ROOT_FOLDER/bulk_geocoder/process_geocoded_csv.py" "$TMP_FOLDER/fire_geocoded.csv" "$TMP_FOLDER/fire_db.csv"

#generate CREATE TABLE statement
csvsql -i postgresql --tables fire --db-schema public -d ',' "$TMP_FOLDER/fire_db.csv" > "$TMP_FOLDER/fire.sql"
#Create table
psql -h $DB_HOST -U $DB_USER -d $DB_NAME < "$TMP_FOLDER/fire.sql"  
#Final processing for table
echo 'Processing table: adding index and unique id...'
psql -h $DB_HOST -U $DB_USER -d $DB_NAME < "$ROOT_FOLDER/etl/fire/process_table.sql"  

#Upload the csv file in the public schema
echo "Uploading fire data to the database..."
cat "$TMP_FOLDER/fire_db.csv" | psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "\COPY public.fire FROM STDIN  WITH CSV HEADER DELIMITER ',';"
echo "Done creating fire table!"