#!/usr/bin/env bash
THREE11_DATA="$DATA_FOLDER/etl/three11"
TMP_FOLDER="$DATA_FOLDER/etl/three11/tmp"

#Read variables from config file
DB_HOST=$(cat $ROOT_FOLDER'/config.yaml' | shyaml get-value db.host)
DB_USER=$(cat $ROOT_FOLDER'/config.yaml' | shyaml get-value db.user)
DB_NAME=$(cat $ROOT_FOLDER'/config.yaml' | shyaml get-value db.database)

#create folder if not exists
mkdir -p $TMP_FOLDER

#Path to update script
UPDATE_SCRIPT=$ROOT_FOLDER/lib_cinci/data_updater/update.py
#Create diff file with entries to upload to the database
$UPDATE_SCRIPT $ROOT_FOLDER/etl/three11/update.yaml

#Clean diff file
python "$ROOT_FOLDER/etl/three11/clean.py"

echo 'Generating CREATE TABLE statement...'
#Generate CREATE TABLE statement
csvsql -i postgresql --tables three11 --db-schema public -d ',' "$TMP_FOLDER/diff_three11_clean.csv" > "$TMP_FOLDER/three11.sql"
#Create table
psql -h $DB_HOST -U $DB_USER -d $DB_NAME < "$TMP_FOLDER/three11.sql"  

echo 'Uploading data...'
#Get list of columns to cpy, this is necessary since we have a PRIMARY KEY
#and we want postgres to take care of those values
COLS="$(head -n 1 $TMP_FOLDER/diff_three11_clean.csv)"
#Upload data to the database
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "\COPY public.three11($COLS) FROM $TMP_FOLDER/diff_three11_clean.csv WITH CSV HEADER DELIMITER ',';"

echo 'Processing table: creating indexes, unique id and geometry column...'
psql -h $DB_HOST -U $DB_USER -d $DB_NAME < "$ROOT_FOLDER/etl/three11/process_table.sql"  

echo 'Done.'
